Update zadanie 2.go
Compilation failed due to following error(s).# command-line-arguments
./main.go:30:23: syntax error: unexpected newline, expecting type